homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Heart of Gold
  auth_providers:
    - type: homeassistant
    # - type: trusted_networks
    #   trusted_networks:
    #     - 172.19.0.0/16
    #     - 10.0.12.0/24
    - type: command_line
      name: LDAP
      command: /config/ldap-auth.sh
      args: ["/config/ldap-auth.cfg"]
      meta: True

frontend:
  javascript_version: auto
  themes: !include_dir_named frontend/themes

panel_iframe: !include_dir_named iframe_panels

recorder: !include recorder.yaml

influxdb: !include influx_db.yaml

remote_homeassistant:
  instances: !include_dir_list remote_instances

logger:
  default: info
  logs:
    homeassistant.components.remote_homeassistant: debug
