homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Heart of Gold
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: command_line
      name: LDAP
      command: /config/ldap-auth.sh
      args: 
        - /config/ldap-auth.cfg

# Notifications
notify: !include_dir_list notifiers
mobile_app:
ios:
  push:
    categories: !include_dir_list ios_push_categories

# Settings
input_number: !include_dir_named input_numbers
input_boolean: !include_dir_named input_booleans

# Templates
binary_sensor: !include_dir_list binary_sensors

camera: !include_dir_list cameras

frontend:
  javascript_version: auto
  themes: !include_dir_named frontend/themes
  extra_module_url:
    - /local/custom_modules/querySelectorDeep.js

http:
  base_url: https://automation.prettybaked.com
  server_port: 8123

panel_iframe: !include_dir_named iframe_panels
panel_custom: !include_dir_list custom_panels

dominos: !include dominos.yaml

recorder: !include recorder.yaml

influxdb: !include influx_db.yaml

history:

map:

twilio: !include twilio.yaml

# remote_homeassistant:
#   instances: !include_dir_list remote_instances

config:

logger:
  default: info

# BEGINHACK
# Prevents issue with servie not found for remote instance
light:
lock:
climate:
switch:
cover:
device_tracker:
person:
fan:
media_player:
alarm_control_panel:
vacuum:
# ENDHACK

mqtt: !include mqtt.yaml
# mqtteventstream: !include eventstream.yaml
mqtt_remoteinstance: !include mqtt_remoteinstance.yaml

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: debug
    homeassistant.components.mqtt_remoteinstance: debug
