homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Main
  auth_providers:
    - type: homeassistant
    - type: command_line
      name: LDAP
      command: /config/ldap-auth.sh
      args: ["/config/ldap-auth.cfg"]
      meta: True

frontend:
  javascript_version: auto
  themes: !include_dir_named frontend/themes

panel_iframe: !include_dir_named iframe_panels

recorder: !include recorder.yaml

influxdb: !include influx_db.yaml

remote_instances: !include_dir_list remote_instances
