homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Heart of Gold
  customize: !include customize.yaml
  # external_url: https://automation.prettybaked.com
  auth_providers:
    - type: homeassistant
    - type: command_line
      name: LDAP
      command: /config/ldap-auth.sh
      args: 
        - /config/ldap-auth.cfg

# Notifications
notify: !include_dir_list notifiers

frontend:
  javascript_version: auto
  themes: !include_dir_named frontend/themes

lovelace:
  mode: yaml
  resources: !include lovelace_resources.yaml
  dashboards: !include_dir_named lovelace_dashboards

http:
  base_url: https://automation.prettybaked.com
  cors_allowed_origins:
    - https://stats.prettybaked.com

panel_iframe: !include_dir_named iframe_panels
panel_custom: !include_dir_list custom_panels

dominos: !include dominos.yaml

recorder: !include recorder.yaml

# influxdb: !include influx_db.yaml

history:

map:

config:

api_proxy: !include api_proxy.yaml
input_boolean: !include_dir_named input_booleans

# BEGINHACK
# Prevents issue with servie not found for remote instance
light:
lock:
climate:
calendar:
switch:
cover:
device_tracker:
person:
fan:
media_player:
alarm_control_panel:
vacuum:
remote:
mobile_app:
# ENDHACK

binary_sensor: !include_dir_list binary_sensors


mqtt: !include mqtt.yaml
mqtteventstream: !include eventstream.yaml
homekit: !include homekit.yaml
