name: Security
host: !secret security_server_host
port: !secret security_server_private_port
secure: false
access_token: !secret security_server_token
subscribe_events:
  - state_changed
  - service_registered