name: settings
host: !secret settings_server_host
port: !secret settings_server_public_port
secure: false
access_token: !secret settings_server_token
subscribe_to:
  - route_registered
  - state_changed
  - service_registered